pipeline:
  name: Build events-app
  identifier: Build_events_app_1772088343879
  projectIdentifier: lab2
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: github2
                    repoName: events-app
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: install dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Bash
                    command: cd events-app && npm install
              - step:
                  type: Run
                  name: run build
                  identifier: run_build
                  spec:
                    shell: Bash
                    command: cd events-app && npm run build
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhubhisbu
                    repo: hisbu/test-events
                    tags:
                      - 1.1.1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: github2
        repoName: events-app
        build: <+input>
